### ISSUE TITLE
REDDITUPLOADS SUPPORT

### ISSUE THREAD

**Issue by az4521** [upnextfm/pienudes#21]
can you support viewing reddituploads images in chat? i need to post my spicy memes.

https://i.reddituploads.com/3792cf5f1d5c4a8e94fd1e4b7371372d?fit=max&h=1536&w=1536&s=07e07ed95ad68e8cdb10255e6fb43a7e

**Comment by upnextfm** [comment]
Embedding the images in chat doesn't work. Reddit must be using hotlink protection.
