### ISSUE TITLE
[Feature Request] Seperate method of communication between users for userscripts

### ISSUE THREAD

**Issue by az4521** [upnextfm/pienudes#33]
basically i want to make a pong game using the chat, but then i realized it would be throttled. if there was a command that i could send in the chat that would cause users to receive a "hidden" message accessible by scripts only, and not throttled like regular chat, p2p user scripts could be implemented over the chat api.

**Comment by upnextfm** [comment]
Yeah, that sounds like a good idea. Would be better than hacking bot communication on top of whispers and such.

**Comment by upnextfm** [comment]
https://scripts.upnext.fm/#topic-api-methods-command  
https://scripts.upnext.fm/#topic-api-events-command
