### ISSUE TITLE
scripts.upnext.fm SSL cert expired

### ISSUE THREAD

**Issue by az4521** [upnextfm/pienudes#38]
time to renew your cert headzoo. also pls roll back 2 person voteskip. shadi had to sit through a 40 minute  video

**Comment by headzoo** [comment]
Alrighty. Heading out for the night, so will knock those two problems out tomorrow.

**Comment by az4521** [comment]
HOLY SHIT YOU RESPONDED.
well thanks. until then though, i wrote a bot and script to voteskip whenever anyone else does
