### ISSUE TITLE
Upnext.FM Cert Expiration + HSTS, site inaccessable

### ISSUE THREAD

**Issue by az4521** [upnextfm/pienudes#40]
headzooooooo pls fix cert

**Comment by headzoo** [comment]
I hate these damn certs. Grr...

**Comment by az4521** [comment]
also now there's a different error, something about socketIO connection failing.

"it appears the socket.io connection has failed. If this error persists, a firewall or antivirus is likely blocking the connection, or the server is down."

in console

"Failed to load resource: net::ERR_INSECURE_RESPONSE" https://upnext.fm:8443/socket.io/socket.io.js

**Comment by headzoo** [comment]
Gonna try to wait it out a bit, and the problem should fix itself.

**Comment by az4521** [comment]
it hasnt fixed itself

**Comment by az4521** [comment]
the service, whatever it is, running at https://upnext.fm:8443/ is still using an expired cert, i doubt it'll fix itself.

**Comment by az4521** [comment]
well NEVERMIND THEN. IT DID.
